### PR TITLE
Merging the changes to the package structure into main

### PR DESCRIPTION
**Pull request by moritzpschwarz**
As discussed, this is the next step in the package development. This does not contain substantial changes but only changes to get the package closer to a CRAN structure.

Automatic testing should now function at the "warn" level and not at the "error" level anymore.

When reviewed and merged into main, further substantial changes can be considered (that are currently e.g. on the new_forecast branch).

This is now the second PR for this - an earlier one was deleted following an error in branch management. This has now been dealt with in #14.

### CODE REVIEW

**Comment by moritzpschwarz** [comment]
Now ready for your review @jkurle, the package structure now follows largely the CRAN requirements.

The automatic tests now only note the superfluous data in data-raw which we can easily delete should we submit it to CRAN eventually.

Once this is merged, I will move more substantial changes to the devel branch.

**Comment by jkurle** [comment]
I had a look and have some comments / changes that I can incorporate but want to quickly check with you:

1. We have many packages in Suggests. Do we want to keep all of them there? Suggests should only have packages that are not required to use most of the functionality. Happy to keep them where they are but then I will add the necessary `requireNamespace()` checks.
2. Why do we export `%>%`? This is only required internally, so I think we should not export it. I can change this but wanted to ask whether there is a specific reason for exporting it.
3. We import `%>%` from two packages. Why? My understanding is that the second import would overwrite the first, i.e. we would only use the one from magrittr anyway.
4. In general, we seem to export most functions. Maybe we should be more conservative and only export a few functions on the user side? Making all even internal functions available to the user means that we need to inform them about any changes to internal handlings and that we cannot easily stop exporting them b/c they might have used them explicitly in their code. Maybe just export `run_model()`, `present_model()`, and the plotting and forecasting methods? 
5. You added `...` as an argument to `run_module()` as parameters to be passed onto `estimate_module()`. But internally `run_module()` does not pass any `...` arguments to `estimate_module()`. Didn't we decide that we would do all argument pass-through explicitly rather than using `...`? Also, `run_module()` does not pass through the argument `use_logs` to `estimate_module()`.

**Comment by moritzpschwarz** [comment]
Thanks Jonas, as always extremely helpful and useful comments. Here my reactions: 


> 1. We have many packages in Suggests. Do we want to keep all of them there? Suggests should only have packages that are not required to use most of the functionality. Happy to keep them where they are but then I will add the necessary `requireNamespace()` checks.

Fair point - I mostly focused on removing packages from `Depends`. But we should really think about which ones we need in `Imports` and which we want in `Suggests`. As a reminder (mostly for myself): Depends is not recommended to use, Imports will install a package alongside the overall package and Suggests will not install a package (but is then needed for specific functions). All this explained [here](https://r-pkgs.org/dependencies-mindset-background.html#sec-dependencies-imports-vs-depends) and [here](https://r-pkgs.org/dependencies-mindset-background.html#sec-dependencies-imports-vs-suggests).

Looking at our packages: 

> Depends: 
>     R (>= 3.5)
> Imports: 
>     gets (>= 0.37),
>     dplyr,
>     tidyr,
>     eurostat,
>     fastDummies,
>     lubridate,
>     rlang,
>     magrittr

I think we really do need all of them - as in I don't think the package would work without them. The ones that we could most easiest replace in my mind would be `lubridate` and maybe `fastDummies` but then we'd need to code those functions up ourselves.

Now to suggests (all just my initial reaction - feel absolutely free to disagree):

**stringr,**
Used a 5 times - potentially replaceable with grep/grepl.

**ggplot2**
Needed for all plots, don't think there is an alternative.

**utils,**
Think we can get rid of this - we only need utils::tail() once (easily replaceable), but then again there is a line in `arrgregate.model.R`: ```## quiets concerns of R CMD check re: the .'s that appear in pipelines
if(getRversion() >= "2.15.1")  utils::globalVariables(c("."))```

**shiny, ggraph, tidygraph, and DT**
Think perfect for Suggests as only needed when actually running the shiny module. Unsure about DT, this is where you are the expert. Can we replace any of them?

**readxl, writexl, and readr,**
potentially replaceable with base functions (only really relevant for the load_or_download function)

**scales,**
Only used to ensure comma formatting - can easily replace this with base function/paste0.

**testthat (>= 3.0.0),**
Don't think we want to change this, right?

**plotly**
New functionality that I think will be quite useful for all produced plots. Would keep as Suggests.

**purrr**
Not currently used but used in new_forecast branch. Will think about replacing.

> 2. Why do we export `%>%`? This is only required internally, so I think we should not export it. I can change this but wanted to ask whether there is a specific reason for exporting it.

This is standard behaviour when using `usethis::use_pipe()` - totally fine for me not to export it.

> 3. We import `%>%` from two packages. Why? My understanding is that the second import would overwrite the first, i.e. we would only use the one from magrittr anyway.
Very true - we do this in two places: once in `aggregate.model.R` and once in `utils-pipe.R`, which is also automatically added by `use_pipe()`. I'm not sure we need `utils-pipe.R`, but I'm not sure. Would be good to check, but yes we'd only want one and only the one from magrittr.

> 4. In general, we seem to export most functions. Maybe we should be more conservative and only export a few functions on the user side? Making all even internal functions available to the user means that we need to inform them about any changes to internal handlings and that we cannot easily stop exporting them b/c they might have used them explicitly in their code. Maybe just export `run_model()`, `present_model()`, and the plotting and forecasting methods?
I think that's reasonable. Also agree with your choices. 

> 5. You added `...` as an argument to `run_module()` as parameters to be passed onto `estimate_module()`. But internally `run_module()` does not pass any `...` arguments to `estimate_module()`. Didn't we decide that we would do all argument pass-through explicitly rather than using `...`? Also, `run_module()` does not pass through the argument `use_logs` to `estimate_module()`.
Yes, agreed - let's remove those. 

So as you see, very much agreeing with you - do you want me to take a shot at the changes or will you have a go? Fine either way for me.

**Comment by jkurle** [comment]
Great, thanks for the feedback! I can have a go!

**Comment by jkurle** [comment]
I'm not too worried about having dependencies (i.e. we don't need to replace packages by base R necessarily). We could still slim it down later but for now, it's most important to have the required packages as Imports and the other ones as Suggests.

I think it should be fine now, good to merge from my side.

**Review by jkurle — APPROVED** [review]

**Comment by moritzpschwarz** [comment]
Excellent, thanks for your changes Jonas - they also work on my Laptop.

**Comment by jkurle** [comment]
Perfect! Let me know if there is something I can help with. E.g. implement in-sample forecasts and evaluation etc.

**Pull request merged**
